### ISSUE TITLE
Module 1 - Content

### ISSUE THREAD

**Issue by nduff08** [dryuen/ist5313-f18-fp2#6]
- Add an apostrophe + s to let in the fourth sentence of the overview. It should read: "For example, let's say...."
- In the second to last line, add 'and Analysis' to the module title so it matches the title shown at the top of the module.
- For question 2, change 'too' to 'to.' It should read: "What is 4 the answer to?"
- Insert a period after the last sentence in the overview.
- For questions 2 and 3, insert a question mark after the question for consistency with question 1.

Suggestions:

- Consider adding bullets to the overview for readability.
- For the mini quiz, consider either including a notification after an answer is selected to show the user whether it is correct or not, or some kind of breakdown at the end of the quiz showing which selections were incorrect.

**Comment by cullenbay** [comment]
Change items as requested. Will try to add feedback to the miniquiz.
