### ISSUE TITLE
Module 2: Content

### ISSUE THREAD

**Issue by chrisolveda** [dryuen/ist5313-f18-fp2#7]
- [ ] Is the **overview page** supposed to provide a brief preview or introduction to the module? Maybe you can provide some learning objectives or important topics the module will encompass?

- [ ] **Mini Quiz (2nd page):** capitalize STAAR in question 1. Add a question mark for question 2. Add a question mark for question 3.

- [ ] **Strategy #1 (3rd page):** “...try to find and answer any question that you can answer” sounds repetitive. How about, “Go to the questions and try to search for any questions that you can answer without reading the passage.”

- [ ] **All of questions in the assessment:** There is a “�” character in all of the questions. Revise and edit.

- [ ] Revise and edit **testing3.js**. The last questions answer is incorrect in your code. It should be “correctAnswer: 2” instead of “correctAnswer: 1”.

**Comment by chrisolveda** [comment]
Wasn't able to create a label for this issue. I don't see a gear icon next to labels.

**Comment by cullenbay** [comment]
Corrected code for testing3.js
