### ISSUE TITLE
Module 2: Multimedia

### ISSUE THREAD

**Issue by chrisolveda** [dryuen/ist5313-f18-fp2#8]
- [ ] Can you center all the images in this module?
- [ ] **Strategy 1 (3rd page):** Suggestion- add an image for an example?
- [ ] **Pat Summit Question 1 (9th page):** The image is not working, so the user cannot answer the question based on the text feature... not sure why it isn't working. I opened it from your zipped files and it worked that way, but doesn't work in Alpha. Not sure what is going on here.

**Comment by cullenbay** [comment]
Added audio to files. Hopefully that clears items up.
