### ISSUE TITLE
Module 2: Usability

### ISSUE THREAD

**Issue by chrisolveda** [dryuen/ist5313-f18-fp2#9]
- [ ] Maybe add a navigation bar in case the user wants to access a previous .html page. Instead of clicking previous several of times, the user can click directly to the desired page.

- [ ] There is a mistake in the assessment. I took the assessment about 7 times and I was not able to get 100%. I believe you only need to get 70% to continue to the next page or to get the certificate. I downloaded the reading passages and answer key from the TEA website and used those answers and still got 91%. I read your html code and it looks like you put G as the correct answer, but on the answer key it says H is the correct answer.

**Comment by cullenbay** [comment]
Group wanted to make everything gated. I understand where you were coming from as it would be nice to add a menu bar so a user does not have to click through the lessons to find where they left off.
